// Country and dial code data for shipping/contact form
export default [
  { code: 'US', name: 'United States', dial_code: '+1', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', dial_code: '+44', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', dial_code: '+1', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', dial_code: '+61', flag: '🇦🇺' },
  { code: 'DE', name: 'Germany', dial_code: '+49', flag: '🇩🇪' },
  { code: 'FR', name: 'France', dial_code: '+33', flag: '🇫🇷' },
  { code: 'IN', name: 'India', dial_code: '+91', flag: '🇮🇳' },
  { code: 'JP', name: 'Japan', dial_code: '+81', flag: '🇯🇵' },
  { code: 'CN', name: 'China', dial_code: '+86', flag: '🇨🇳' },
  { code: 'SG', name: 'Singapore', dial_code: '+65', flag: '🇸🇬' },
  { code: 'IE', name: 'Ireland', dial_code: '+353', flag: '🇮🇪' },
  { code: 'BR', name: 'Brazil', dial_code: '+55', flag: '🇧🇷' },
  { code: 'ZA', name: 'South Africa', dial_code: '+27', flag: '🇿🇦' },
  { code: 'NZ', name: 'New Zealand', dial_code: '+64', flag: '🇳🇿' },
  { code: 'IT', name: 'Italy', dial_code: '+39', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', dial_code: '+34', flag: '🇪🇸' },
  { code: 'SE', name: 'Sweden', dial_code: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', dial_code: '+41', flag: '🇨🇭' },
  { code: 'NL', name: 'Netherlands', dial_code: '+31', flag: '🇳🇱' },
  { code: 'BE', name: 'Belgium', dial_code: '+32', flag: '🇧🇪' },
  { code: 'DK', name: 'Denmark', dial_code: '+45', flag: '🇩🇰' },
  { code: 'NO', name: 'Norway', dial_code: '+47', flag: '🇳🇴' },
  { code: 'FI', name: 'Finland', dial_code: '+358', flag: '🇫🇮' },
  { code: 'RU', name: 'Russia', dial_code: '+7', flag: '🇷🇺' },
  { code: 'KR', name: 'South Korea', dial_code: '+82', flag: '🇰🇷' },
  { code: 'MX', name: 'Mexico', dial_code: '+52', flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina', dial_code: '+54', flag: '🇦🇷' },
  { code: 'TR', name: 'Turkey', dial_code: '+90', flag: '🇹🇷' },
  { code: 'PL', name: 'Poland', dial_code: '+48', flag: '🇵🇱' },
  { code: 'GR', name: 'Greece', dial_code: '+30', flag: '🇬🇷' },
  { code: 'PT', name: 'Portugal', dial_code: '+351', flag: '🇵🇹' },
  { code: 'IL', name: 'Israel', dial_code: '+972', flag: '🇮🇱' },
  { code: 'SA', name: 'Saudi Arabia', dial_code: '+966', flag: '🇸🇦' },
  { code: 'AE', name: 'United Arab Emirates', dial_code: '+971', flag: '🇦🇪' },
  { code: 'EG', name: 'Egypt', dial_code: '+20', flag: '🇪🇬' },
  { code: 'TH', name: 'Thailand', dial_code: '+66', flag: '🇹🇭' },
  { code: 'MY', name: 'Malaysia', dial_code: '+60', flag: '🇲🇾' },
  { code: 'ID', name: 'Indonesia', dial_code: '+62', flag: '🇮🇩' },
  { code: 'PH', name: 'Philippines', dial_code: '+63', flag: '🇵🇭' },
  { code: 'NG', name: 'Nigeria', dial_code: '+234', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', dial_code: '+254', flag: '🇰🇪' },
  { code: 'GH', name: 'Ghana', dial_code: '+233', flag: '🇬🇭' },
  { code: 'PK', name: 'Pakistan', dial_code: '+92', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', dial_code: '+880', flag: '🇧🇩' },
  { code: 'LK', name: 'Sri Lanka', dial_code: '+94', flag: '🇱🇰' },
  { code: 'VN', name: 'Vietnam', dial_code: '+84', flag: '🇻🇳' },
  { code: 'TW', name: 'Taiwan', dial_code: '+886', flag: '🇹🇼' },
  { code: 'HK', name: 'Hong Kong', dial_code: '+852', flag: '🇭🇰' },
  { code: 'AT', name: 'Austria', dial_code: '+43', flag: '🇦🇹' },
  { code: 'CZ', name: 'Czech Republic', dial_code: '+420', flag: '🇨🇿' },
  { code: 'HU', name: 'Hungary', dial_code: '+36', flag: '🇭🇺' },
  { code: 'RO', name: 'Romania', dial_code: '+40', flag: '🇷🇴' },
  { code: 'SK', name: 'Slovakia', dial_code: '+421', flag: '🇸🇰' },
  { code: 'BG', name: 'Bulgaria', dial_code: '+359', flag: '🇧🇬' },
  { code: 'HR', name: 'Croatia', dial_code: '+385', flag: '🇭🇷' },
  { code: 'SI', name: 'Slovenia', dial_code: '+386', flag: '🇸🇮' },
  { code: 'EE', name: 'Estonia', dial_code: '+372', flag: '🇪🇪' },
  { code: 'LV', name: 'Latvia', dial_code: '+371', flag: '🇱🇻' },
  { code: 'LT', name: 'Lithuania', dial_code: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', dial_code: '+352', flag: '🇱🇺' },
  { code: 'IS', name: 'Iceland', dial_code: '+354', flag: '🇮🇸' },
  { code: 'MT', name: 'Malta', dial_code: '+356', flag: '🇲🇹' },
  { code: 'CY', name: 'Cyprus', dial_code: '+357', flag: '🇨🇾' },
  { code: 'MC', name: 'Monaco', dial_code: '+377', flag: '🇲🇨' },
  { code: 'LI', name: 'Liechtenstein', dial_code: '+423', flag: '🇱🇮' },
  { code: 'SM', name: 'San Marino', dial_code: '+378', flag: '🇸🇲' },
  { code: 'VA', name: 'Vatican City', dial_code: '+39', flag: '🇻🇦' },
  // ... add more as needed
]; 