[package]
name = "bux-claim-minimal"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.0"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
solana-program-test = "1.18.0"
solana-sdk = "1.18.0" 